services:
# Servicio 1 - API REST
  backend:
    build: ./backend        # Ruta al Dockerfile del Servicio 1
    container_name: api-rest-service
    ports:
      - "5000:5000"         # Expone puerto 5000 (Host:Contenedor)
    networks:
      - app-network
    environment:
      - DB_HOST=database    # Preparación para conectar con Servicio 2
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_NAME=proyecto_db
    depends_on:
      - database # Fin servicio 1 - API REST

# Servicio 2 - Base de Datos PostgreSQL
  database:
    image: postgres:15
    container_name: db_proyecto
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=proyecto_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

# Servicio 3 - Frontend web
  frontend:
    build: ./frontend   # Ruta al Dockerfile del Servicio 3
    container_name: web-frontend    # Nombre del contenedor
    ports:    # Mapaeo de puertos
      - "8080:80"
    networks:   # Conexión a la red
      - app-network
    depends_on:   # Dependencias, orden de encendido
      - backend

# Configuraciones globales para los servicios
volumes:
  db_data: # Persistencia de datos para PostgreSQL

networks:
  app-network:
    driver: bridge
